-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rfc" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "razonSocial" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "usoCFDI" TEXT DEFAULT 'G03';
