ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "condition" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "parkingType" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "parkingSpaces" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "miniSplits" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "yearBuilt" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "floors" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "lotSize" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "maintenanceFee" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "halfBaths" INTEGER;
